#!/bin/bash
# Quick checklist for Railway login fix

echo "🔍 Railway Environment Variables Checklist"
echo "=========================================="
echo ""
echo "Make sure these are set in your Railway Dashboard:"
echo "(Settings → Environment)"
echo ""
echo "✅ NEXTAUTH_URL=https://online-interview.up.railway.app"
echo "✅ NEXTAUTH_SECRET=test-secret-key-for-development-only-change-in-production"
echo "✅ ADMIN_EMAIL=admin@gmail.com"
echo "✅ ADMIN_PASSWORD=admin123"
echo "✅ MONGODB_URI=<your mongodb connection string>"
echo "✅ CLOUDINARY_CLOUD_NAME=<your cloudinary cloud name>"
echo "✅ CLOUDINARY_API_KEY=<your cloudinary api key>"
echo "✅ CLOUDINARY_API_SECRET=<your cloudinary api secret>"
echo "✅ NODE_ENV=production"
echo ""
echo "⚠️  CRITICAL: NEXTAUTH_URL must include the protocol (https://)"
echo "❌ Wrong: online-interview.up.railway.app"
echo "✅ Correct: https://online-interview.up.railway.app"
echo ""
echo "After setting all variables:"
echo "1. Redeploy your app"
echo "2. Wait for deployment to complete"
echo "3. Test login at: https://online-interview.up.railway.app/login"
echo ""
echo "If still not working, check Railway logs for errors"
